# Generated by Django 3.2 on 2023-02-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetachedHouseRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('지역코드', models.TextField(blank=True, null=True)),
                ('법정동', models.TextField(blank=True, null=True)),
                ('건축년도', models.BigIntegerField(blank=True, null=True)),
                ('계약면적', models.FloatField(blank=True, null=True)),
                ('년', models.BigIntegerField(blank=True, null=True)),
                ('월', models.BigIntegerField(blank=True, null=True)),
                ('일', models.BigIntegerField(blank=True, null=True)),
                ('보증금액', models.BigIntegerField(blank=True, null=True)),
                ('월세금액', models.BigIntegerField(blank=True, null=True)),
                ('계약구분', models.TextField(blank=True, null=True)),
                ('계약기간', models.TextField(blank=True, null=True)),
                ('갱신요구권사용', models.TextField(blank=True, null=True)),
                ('종전계약보증금', models.BigIntegerField(blank=True, null=True)),
                ('종전계약월세', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '단독다가구전월세',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetachedHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('지역코드', models.TextField(blank=True, null=True)),
                ('법정동', models.TextField(blank=True, null=True)),
                ('지번', models.TextField(blank=True, null=True)),
                ('주택유형', models.TextField(blank=True, null=True)),
                ('건축년도', models.BigIntegerField(blank=True, null=True)),
                ('대지면적', models.FloatField(blank=True, null=True)),
                ('연면적', models.FloatField(blank=True, null=True)),
                ('년', models.BigIntegerField(blank=True, null=True)),
                ('월', models.BigIntegerField(blank=True, null=True)),
                ('일', models.BigIntegerField(blank=True, null=True)),
                ('거래금액', models.BigIntegerField(blank=True, null=True)),
                ('거래유형', models.TextField(blank=True, null=True)),
                ('중개사소재지', models.TextField(blank=True, null=True)),
                ('해제사유발생일', models.TextField(blank=True, null=True)),
                ('해제여부', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '단독다가구매매',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
